<a href="https://colab.research.google.com/github/rammya29/Goeduhub-STP/blob/main/Assignment_Task_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Assignment / Task - 4**

##Question on Numpy

1. Import the numpy package under the name np and Print the numpy version and the configuration 

In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None




---



2. Create a null vector of size 10

In [2]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]




---



3. Create Simple 1-D array and check type and check data types in array

In [3]:
import numpy as np
x = np.arange(10,21)
print('Type : ' ,type(x))
print('Datatype : ', x.dtype)

Type :  <class 'numpy.ndarray'>
Datatype :  int64




---



4. How to find number of dimensions, bytes per element and bytes of memory used?

In [4]:
import numpy as np
x = np.arange(12).reshape((3, 4))
print("Dimension of the array: ",x.ndim)
print("Memory size of one array element in bytes: ",x.itemsize)
print("Memory size of numpy array in bytes: ", x.nbytes)

Dimension of the array:  2
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes:  96




---



5. Create a null vector of size 10 but the fifth value which is 1

In [5]:
import numpy as np
x = np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]




---



6. Create a vector with values ranging from 10 to 49

In [6]:
import numpy as np
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]




---



7. Reverse a vector (first element becomes last)

In [7]:
import numpy as np
x = np.arange(12, 20)
print(x)
x = x[::-1]
print(x)

[12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12]




---



8. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
import numpy as np
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]




---



9. Find indices of non-zero elements from `[1,2,0,0,4,0]`

In [9]:
import numpy as np
c=[1,2,0,0,4,0]
x = np.nonzero(c)
print("Indices of non-zero element is : ", x)

Indices of non-zero element is :  (array([0, 1, 4]),)




---



10. Create a 3x3 identity matrix

In [10]:
import numpy as np
x = np.identity(3) #np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]




---



11. Create a 3x3x3 array with random values

In [11]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.50187433 0.08848414 0.18084455]
  [0.92025897 0.51752737 0.1638718 ]
  [0.65457621 0.68196766 0.25418765]]

 [[0.35957945 0.38724863 0.71661744]
  [0.5617879  0.393631   0.35654405]
  [0.92681898 0.64785592 0.43664492]]

 [[0.7361429  0.27384369 0.94468644]
  [0.1934857  0.37641298 0.62273381]
  [0.47653998 0.50458154 0.94146658]]]




---



12. Create a 10x10 array with random values and find the minimum and maximum values

In [12]:
import numpy as np
x = np.random.random(100).reshape(10,10)
print(x)
print("Maximum Value is : " , x.max())
print("Minimum Value is : " , x.min())

[[0.49560208 0.03092801 0.88242211 0.39849981 0.89357009 0.41183155
  0.81886153 0.2889649  0.84523198 0.20241739]
 [0.81458068 0.06779215 0.47292178 0.69183007 0.6385042  0.18726843
  0.36360617 0.33574465 0.51978895 0.75883818]
 [0.69131494 0.46465598 0.1454426  0.85263347 0.46148135 0.61996827
  0.72152257 0.81473197 0.7304744  0.96481319]
 [0.64134781 0.75933473 0.47622912 0.39785817 0.91827616 0.65663092
  0.45795734 0.10315493 0.96608068 0.06945823]
 [0.80197446 0.10880692 0.66176585 0.90559911 0.97964477 0.84100628
  0.57993523 0.31627268 0.0491552  0.39390671]
 [0.89958533 0.41455342 0.3150914  0.35507068 0.62633953 0.21637593
  0.92161941 0.46019366 0.9741254  0.31542909]
 [0.38247414 0.69645432 0.94806165 0.48760505 0.29823462 0.82327216
  0.90536068 0.22072191 0.02889832 0.94890913]
 [0.58969284 0.14596775 0.94706764 0.41805039 0.8146248  0.91645416
  0.50165894 0.94238085 0.6696549  0.06051658]
 [0.27371748 0.19508371 0.67979484 0.80178029 0.77588193 0.60812919
  0.14739357



---



13. Create a random vector of size 30 and find the mean value

In [13]:
import numpy as np
x = np.random.random(30)
print(x)
print("Mean is : ",x.mean())

[0.36848726 0.63641026 0.01722626 0.20727061 0.63015573 0.60830726
 0.78660223 0.3064552  0.86391697 0.86483334 0.71684652 0.94308587
 0.08829887 0.65019655 0.31402597 0.08051258 0.28053336 0.96841523
 0.53372636 0.4754189  0.7099017  0.69680137 0.81915373 0.08680677
 0.47614069 0.86057209 0.97126205 0.12399113 0.50466047 0.960123  ]
Mean is :  0.5516712778101236




---



14. Create a 2d array with 1 on the border and 0 inside

In [14]:
import numpy as np
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]




---



15. How to add a border (filled with 0's) around an existing array? 

In [15]:
import numpy as np
x = np.zeros((5,5))
x[1:-1,1:-1] = 1
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]




---



16. How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

 Example -
`[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]`

In [16]:
import numpy as np
x = np.arange(1,15).reshape(2,7)
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


   * **Get 13** 

In [17]:
print(x[1,5])

13


  * **Get first row only**

In [18]:
print(x[0,:])

[1 2 3 4 5 6 7]


   *  **Get 3rd column only**

In [19]:
print(x[:,3])

[ 4 11]


  * **Get `[2, 4, 6]`**

In [20]:
print(x[0,1::2])

[2 4 6]


  * **Replace 13 by 20**

In [21]:
x[1,5]=20
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]




---



17. How to Convert a 1D array to a 2D array with 2 rows

In [22]:
import numpy as np
x = np. array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np. reshape(x, (2, 5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]




---



18. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

 Input: `a = np.array([1,2,3])`

 Desired Output: `array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`

In [23]:
import numpy as np
a = np.array([1,2,3])
a = np.append(np.repeat(a,3),np.tile(a,3))
print(a)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]




---



19. Write a program to show how Numpy taking less memory compared to Python List?

In [24]:
import numpy as np
import sys
array = np.arange(10)
print("Size of NumPy array: ", array.itemsize * array.itemsize)
list1 = range(0, 10)
print("Size of list: ", sys.getsizeof(1)*len(list1))

Size of NumPy array:  64
Size of list:  280




---



20. Write a program to show how Numpy taking less time compared to Python List?

In [25]:
import numpy as np
import time
import sys
Size = 100000
list1 = range(Size)
list2 = range(Size)
arr1 = np.arange(Size)
arr2 = np.arange(Size)
start = time.time()
result = [(x * y) for x, y in zip(list1, list2)]        
print("Time for Python List in msec: ", (time.time() - start) * 1000)
start = time.time()
result = arr1 * arr2
print("Time for NumPy array in msec: ", (time.time()- start) * 1000)

Time for Python List in msec:  17.47584342956543
Time for NumPy array in msec:  1.901388168334961




---



#End Of Assignment

**Author** : Rammya Dharshini K

**Date** : 27 - 05 - 2021

**Reg.ID** : GO_STP_1613