<a href="https://colab.research.google.com/github/rammya29/Goeduhub-STP/blob/main/Assignment_Task_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment / task - 9

Predict retention of an employee within an organization such that whether the employee will leave the company or continue with it. An organization is only as good as its employees, and these people are the true source of its competitive advantage. Dataset is downloaded from Kaggle

Link: https://www.kaggle.com/giripujar/hr-analytics



First do data exploration and visualization, after this create a logistic regression model to predict Employee Attrition Using Machine Learning & Python.

Importing Required modules

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('/content/HR_comma_sep.csv')
data.head()

satisfaction_level  last_evaluation  ...  Department  salary
0                0.38             0.53  ...       sales     low
1                0.80             0.86  ...       sales  medium
2                0.11             0.88  ...       sales  medium
3                0.72             0.87  ...       sales     low
4                0.37             0.52  ...       sales     low

[5 rows x 10 columns]

Analyze data

In [5]:
data.shape

(14999, 10)

In [6]:
data.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'Department', 'salary'],
      dtype='object')

In [7]:
data.describe()

satisfaction_level  last_evaluation  ...          left  promotion_last_5years
count        14999.000000     14999.000000  ...  14999.000000           14999.000000
mean             0.612834         0.716102  ...      0.238083               0.021268
std              0.248631         0.171169  ...      0.425924               0.144281
min              0.090000         0.360000  ...      0.000000               0.000000
25%              0.440000         0.560000  ...      0.000000               0.000000
50%              0.640000         0.720000  ...      0.000000               0.000000
75%              0.820000         0.870000  ...      0.000000               0.000000
max              1.000000         1.000000  ...      1.000000               1.000000

[8 rows x 8 columns]

In [8]:
data.isnull().sum()

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
Department               0
salary                   0
dtype: int64

Model

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() 

In [11]:
data.Department = le.fit_transform(data.Department)
data.Department.unique()

array([7, 2, 3, 9, 8, 4, 0, 6, 5, 1])

In [13]:
data.salary = le.fit_transform(data.salary)
data.salary.unique()

array([1, 2, 0])

In [14]:
x = data.drop(['salary'],axis = 1)
y = data['salary']

In [15]:
import sklearn
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 1/4, random_state = 1)

In [17]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [18]:
y_pred = model.predict(x_test)
y_pred

array([2, 1, 1, ..., 2, 1, 2])

In [19]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)

In [20]:
df = pd.DataFrame({'Actual' : y_test, 'Predicted' : y_pred})
df

Actual  Predicted
11908       2          2
10508       2          1
9193        1          1
13087       1          1
506         2          1
...       ...        ...
4828        1          2
4939        2          1
9628        2          2
2195        1          1
13772       2          2

[3750 rows x 2 columns]

#End Of Assignment

**Author** : K Rammya Dharshini

**Date** : 09-06-2021

**Reg.ID** : GO_STP_1613